services:
  control:
    container_name: jepsen-kiwidb-control
    hostname: control
    build: control
    command: ["ping", "127.0.0.1"]
    env_file:
      - secret/keys.env
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
    volumes:
      - ../../jepsen-kiwidb:/jepsen-kiwidb
  n1:
    container_name: jepsen-kiwidb-n1
    build: node
    privileged: true
    hostname: n1
    env_file: secret/keys.env
  n2:
    extends: n1
    container_name: jepsen-kiwidb-n2
    hostname: n2
  n3:
    extends: n1
    container_name: jepsen-kiwidb-n3
    hostname: n3
  n4:
    extends: n1
    container_name: jepsen-kiwidb-n4
    hostname: n4
  n5:
    extends: n1
    container_name: jepsen-kiwidb-n5
    hostname: n5
